/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ModalCmp: typeof import('./src/components/page/page-modal/modal-cmp.vue')['default']
    OperationCmp: typeof import('./src/components/page/page-operation/operation-cmp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableCmp: typeof import('./src/components/page/page-table/table-cmp.vue')['default']
  }
}
